- name: Install mysql on centos and rhel
  yum: name={{ centos_sql }}  state=present
  when: ansible_distribution == 'CentOS'  or ansible_distribution == 'Redhat'

- name: Start mysql in centos and rhel
  service: name={{ service_sql }}  state=started

  ## This dependency need to be installed ##
  #- name: Install python pip dependency for mysql to work
  #  yum: name=python-pip    start=present

  #- name: Install python devel package for mysql to work
  #  yum: name=python-devel   state=present

  #- name: Install mysql devel package for mysql to work
  #  yum: name=mysql-devel   state=present

- name: Install ansible package dependency for mysql
  yum:  name={{ mysql_package }}  state=present

