---
# tasks file for firewall 
# This task can ONLY be done on an in premise rhel/centos server 
- name: Configure firewall
  lineinfile:
          path: /etc/sysconfig/iptables
          regexp: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
          inserafter: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
          line: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT'

