---
# tasks file for wordpress

- name: Download and extract wordpress
  unarchive:
        src: "{{ w_url }}"  # https://wordpress.org/wordpress-5.1.1.tar.gz
        dest: "{{ dest_url }}"  # /tmp  
        remote_src: yes

- name: Copy wordpress
  copy:
     src: "{{ dest_url2 }}"  # /tmp/wordpress
     dest: "{{ DocRoot }}"  #/var/www/html
     owner: "{{ owner_name }}" # apache
     group: "{{ group_owner }}"  #apache
     remote_src: yes
  notify:
       - restart apache

- name: Configure Database connection
  command: "{{ item }}"
  with_items:
                  - cp /var/www/html/wordpress/wp-config-sample.php  /var/www/html/wordpress/wp-config.php
                  - sed -i "s/^define( 'DB_NAME',.*/define( 'DB_NAME', 'webserver' );/" /var/www/html/wordpress/wp-config.php
                  - sed -i "s/^define( 'DB_USER',.*/define( 'DB_USER', 'oracle' );/" /var/www/html/wordpress/wp-config.php
                  - sed -i "s/^define( 'DB_PASSWORD',.*/define( 'DB_PASSWORD', 'school1' ):/" /var/www/html/wordpress/wp-config.php


