---
# tasks file for wordpress

- name: Download and extract wordpress
  unarchive:
        src: "{{ w_url }}"          # https://wordpress.org/wordpress-5.1.1.tar.gz
        dest: "{{ dest_url }}"      # /tmp  
        remote_src: yes

- name: Copy wordpress
  copy:
     src: "{{ dest_url2 }}"         # /tmp/wordpress
     dest: "{{ DocRoot }}"          #/var/www/html
     owner: "{{ owner_name }}"      # apache
     group: "{{ group_owner }}"     #apache
     remote_src: yes
  notify:
       - restart apache

- name: Create the directory uploads
  file:
    path: /var/www/html/wordpress/wp-content/uploads
    state: directory
   
- name: Replace wp-config-sample.php by wp-config.php
  copy:
    src: /var/www/html/wordpress/wp-config-sample.php
    dest: /var/www/html/wordpress/wp-config.php
    remote_src: yes

- name: Go into the html directory
  command: 
    cmd: /var/www/html  
    creates: /var/www/html

#- name: Copy all the wordpress content in to the html directory
#  copy:
#   src: /var/www/html/wordpress
#   dest: /var/www/html
#   remote_src: yes

- name: Copy all the wordpress content in to the html directory
  command: cp -r /var/www/html/wordpress/.    /var/www/html

- name: Change the owner and group owner of all files and directories to be apache
  command: chown  -R  apache:apache  /var/www/html

- name: Change permission of all the files
  command: chmod 755 /var/www/html/wp-content/.

  # win_owner:
    # path: /var/www/html
    # user: apache
    # group: apache
    # recurse: yes

- name: Configure Database connection
  command: "{{ item }}"
  with_items:
                 # - cp -r  /var/www/html/wordpress/.      /var/www/html
                 # - rm -rf /var/www/html/wordpress
                 # - chown -R apache:apache  /var/www/html
                 # - cp  /var/www/html/wordpress/wp-config-sample.php  /var/www/html/wordpress/wp-config.php 
                 # - cd  /var/www/html
                 # - cp -r /var/www/html/wordpress/*    /var/www/html
                 # - cp  -r wordpress/* .
                 # - mkdir  /var/www/html/wp-content/uploads
                 # - cd   /var/www/html/wp-content   
                 # - mkdir uploads
                 # - chown -R  apache:apache  /var/www/html/* 

                  - rm -rf /var/www/html/wordpress

                  - sed -i "s/^define( 'DB_NAME',.*/define( 'DB_NAME', 'webserver' );/" /var/www/html/wp-config.php
                  - sed -i "s/^define( 'DB_USER',.*/define( 'DB_USER', 'oracle' );/" /var/www/html/wp-config.php
                  - sed -i "s/^define( 'DB_PASSWORD',.*/define( 'DB_PASSWORD', 'school1' ):/" /var/www/html/wp-config.php


